import "./globals.css";
import logo from "../public/logo.png";
import Image from "next/image";

export const metadata = {
  title: "Elliot Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content={metadata.description} />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin={""}
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat&family=Playfair+Display:wght@600&display=swap"
          rel="stylesheet"
        />
        <title>{metadata.title}</title>
      </head>
      <body>
        <header
          className={"flex flex-row justify-around items-center w-full mt-3"}
        >
          <a
            className={
              "text-lg font-montserrat border-b-2 border-b-white transition-colors ease-in-out delay-150 hover:border-b-black"
            }
            href={"/"}
          >
            Номера
          </a>
          <a
            className={
              "text-lg font-montserrat border-b-2 border-b-white transition-colors ease-in-out delay-150 hover:border-b-black"
            }
            href={"/"}
          >
            Бронирование
          </a>
          <a href={"/"}>
            <Image height={90} width={90} src={logo} alt={"logo"} />
          </a>
          <a
            className={
              "text-lg font-montserrat border-b-2 border-b-white transition-colors ease-in-out delay-150 hover:border-b-black"
            }
            href={"/"}
          >
            Контакты
          </a>
          <a
            className={
              "text-lg font-montserrat border-b-2 border-b-white transition-colors ease-in-out delay-150 hover:border-b-black"
            }
            href={"/"}
          >
            Отзывы
          </a>
        </header>
        {children}
      </body>
    </html>
  );
}
